import Head from 'next/head'
import { useEffect, useState } from 'react'
import ContactPagination from '../../components/coinlist/contactPagination';
import Button from '../../components/ui/button';
import AdminMainHeader from "../../components/layout/admin-header"






export default  function Home() {
  const [isLoading, SetIsLoading] = useState(false);
  const [data, SetData]=useState([]);
  const [promoteddata, SetPromotedData]=useState([]);
  const [count,setCount]=useState(0);
  const [isVote, setVote]=useState(true);
 

  const refetch=()=>{
    fetch(process.env.NEXT_PUBLIC_CONTACT_MESSAGE_LIST)
    .then(res=>res.json())
    .then((data)=>{
        //console.log("kkk",data.contactmsg)
        SetData(data);
     setCount(count+1); 
    //   SetPromotedData(data.promoted)
})
    
   
    // SetIsLoading(true)
  }


  useEffect(()=>{ 
   refetch();

  },[count])


  if(!isLoading){
    <div>
      Loading ....
    </div>
  }

  if(!data) {
    <div>
      No Data...
    </div>
  }

  return (
    <div className='bg-bodygray'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />

        <link
      href="https://fonts.googleapis.com/css2?family=Poppins:ital@0;1&display=swap"
      rel="stylesheet"
       />
       <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" /> 
      </Head>

      <div>
      <AdminMainHeader  />
      </div>
   
   <ContactPagination data={data} />
   
    </div>

    
  )

  
}